apiVersion: multitenancy.metricsadvisor.ai/v1
kind: AppService
metadata:
  name: appservice-sample
spec:
  totalReplicas: 9
  replicaPolicy: avg
  deploymentSpec:
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
          - containerPort: 80
  serviceSpec:
    selector:
      app: nginx
    ports:
      - protocol: TCP
        port: 80
        targetPort: 9376
  roleTemplate:
    kind: ClusterRole
    metadata:
      name: kensho2-watchdog-clusterRole
    rules:
    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
