apiVersion: multitenancy.metricsadvisor.ai/v1
kind: AppService
metadata:
  name: appservice-sample
spec:
  totalReplicas: 9
  replicaPolicy: avg
  deploymentSpec:
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
          - containerPort: 80
  serviceSpec:
    selector:
      app: nginx
    ports:
      - protocol: TCP
        port: 80
        targetPort: 9376
  roleTemplate:
    kind: Role
    metadata:
      name: kensho2-watchdog-clusterRole
    rules:
    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  roleBindingTemplate:
    kind: RoleBinding
    metadata:
      name: kensho2-watchdog-binding
    subjects:
    - kind: User
      name: Jinrui
      apiGroup: rbac.authorization.k8s.io
    roleRef:
      kind: ClusterRole
      name: kensho2-watchdog-clusterRole
      apiGroup: rbac.authorization.k8s.io
  virtualServiceSpec:
    hosts:
    - jinrzhantest
    http:
    - name: appservice-sample
      match:
      - uri:
        prefix: /appservice-sample/
      rewrite:
        uri: /
      route:
      - destination:
          host: appservice-sample-svc.default.svc.cluster.local
